import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import FetchExample1 from "./FetchExample1";
import FetchExample2 from "./FetchExample2";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <FetchExample1/>
        <Link
              href={"./FetchExample2"}
        ></Link>
      </main>
    </>
  );
};

export default Home;
